# Generated by Django 3.1.5 on 2021-01-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201129_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
