# Generated by Django 3.1.5 on 2021-03-01 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_siteuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
